- src/flags/team.ts
- test/flags/team.test.ts
This PR fixes the priority so that the team flag goes in priority of:
1. value passed into team flag
Then from  flag's `default()`:
2. value passed into org flag
3. team environment variable
4. org environment variable
* This PR is part of a [bigger PR fix at `heroku/cli`](https://github.com/heroku/cli/pull/1250) and should be merged along with that.
> fix: prioritize flags above env variables for the team flag default value

- package.json
- yarn.lock
Includes fix in `heroku-client` for deprecation warnings in Node 12.
> chore: bump heroku-client

- src/login.ts
- test/login.test.ts
When using Login with interactive, and API returns an error with an id of `device_trust_required`, we should return a custom error body with the text "The interactive flag requires Two-Factor Authentication to be enabled on your account. Please use heroku login."
GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007t6OqIAI/view
> feat: Override error message for login device_trust_required

- src/login.ts
This will make it easier to open URLs in terminals that turn the text into a link when they are on a new line.
> fix(login): put url on a separate lines so they can be clicked

- package.json
- src/api-client.ts
- src/request-id.ts
- test/api-client.test.ts
- test/request-id.test.ts
- yarn.lock
Track and thread request IDs when using the API client
* Each request gets a new request ID
* Each request includes the subsequent request IDs, separated by a comma with the newly created request ID being first
* Each response for a request will add new request IDs that are not already tracked
> feat: add request ID threading

- src/api-client.ts
- test/api-client.test.ts
This PR fixes the issue uncovered in https://heroku.support/962316
When a user is providing their own API key using the `HEROKU_API_KEY` environment variable, it's possible for them to get into an awkward state if that key is actually invalid. In the case that it's invalid, the API will return a 401, which will trigger a code path that will ultimately attempt to initiate a new login flow in order for the user to re-authenticate and continue using the CLI.
*However*, the bug here is that the login flow itself checks to see `HEROKU_API_KEY` has been set and immediately bails if it has (e.g. https://github.com/heroku/heroku-cli-command/blob/cfreeman/tweak-login-error-handling/src/login.ts#L43-L44), reporting to the user that they cannot login when `HEROKU_API_KEY` is set, even though the …
> don’t attempt login flow when api key is set

- src/login.ts
- test/login.test.ts
We have [an open PR to front_end_auth that reduces CLI login token expiration to 30 days](https://github.com/heroku/front_end_auth/pull/243). This is to also limit the `--interactive` logins to the same amount.
Since an expiration time can be specified, I've added some code to reject any provided value that is greater than 30 days.
This is a requirement for consistency across Salesforce.
[GUS](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07AH000000BD07YAG)
> Limit Interactive Logins to 30 Days

- .eslintrc
- .github/workflows/ci.yml
- examples/login.ts
- examples/logout.ts
- package.json
- src/api-client.ts
- src/command.ts
- src/completions.ts
- src/deps.ts
- src/file.ts
- src/flags/app.ts
- src/flags/team.ts
- src/git.ts
- src/index.ts
- src/login.ts
- src/mutex.ts
- src/vars.ts
- test/api-client.test.ts
- test/command.test.ts
- test/flags/app.test.ts
- test/flags/org.test.ts
- test/flags/pipeline.test.ts
- test/flags/team.test.ts
- test/git.test.ts
- test/login.test.ts
- test/mutex.test.ts
- tslint.json
- yarn.lock
Fix remaining packages and tests.
Added `cli-ux` dependency back for believed intended purpose `deprecatedCLI`
Revert back to tslint from eslint.
> fix: oclif core migration remaining packages

- src/command.ts
- tsconfig.json
Fixes an issue with the `build` command that would output the files in the `src` directory into a `src` directory inside the `lib` directory, instead of directly inside the `lib` directory. See [Slack convo](https://salesforce-internal.slack.com/archives/C01LKDT1P6J/p1669239615684489) for more info.
> fix: fix pjson import and remove option from tsconfig

- .github/workflows/ci.yml
Updating GH actions/checkout to use v3
> chore: update gh actions/checkout to v3

- .github/workflows/ci.yml
Updating our GH actions CI config so that it
- runs on push to all branches
- runs against windows, ubuntu, and macos
- uses v3 of both actions/checkout and actions/setup-node
- uses node version 17
> chore: update gh actions CI config

- package.json
- yarn.lock
Necessary to complete the Heroku CLI oclif migration epic:https://gus.lightning.force.com/lightning/r/ADM_Epic__c/a3QEE000000OzFF2A0/view
> chore: upgrade oclif core to 1.26.2

- package.json
- yarn.lock
We need to bump `@oclif/core` to version 2.16.0 for CLI in order to use `hiddenAliases` property in command configuration, but that breaks CLI builds because of the dependency on this package.
`@oclif/core` introduces changes in configuration types for Command class that makes types incompatible between versions 2.15.0 and 2.16.0.
Required for this [GUS Work Item](https://gus.lightning.force.com/a07EE00001pJYQ3YAO) completion (Heroku internal)
> Bumping @oclif/core version to 2.16.0

- .gitignore
- package.json
- src/command.ts
- yarn.lock
This PR provides the `allowArbitraryFlags` boolean which provides backwards compatibility for commands that should allow unspecified flags to be passed to a child process
1. Checkout this branch, install and build
2. Link to the main Heroku CLI or somehow install the build output as a dependency
3. Pick a command and set the `allowArbitraryFlags` to true
4. run the command with arbitrary flags.
> fix(W-16338640): Backward compatibility for CLI commands

- src/command.ts
- yarn.lock
This PR adds a deprecation warning when backwards compatible syntax is applied by the user. In addition, this PR adds a check for `nonExistentFlags` so that if a user forgets arguments required for the command, the command won't throw an iteration error when iterating through this array.
> fix(W-16338640): Update backwards compatibility for CLI commands

- src/command.ts
This PR fixes a bug discovered in the backwards compatibility logic where the passed positional flags aren't consumed by the `heroku addons:create` command. While this logic enables the proper consumption of positional flags, it should be noted that this implementation is temporary until the next major release of the Heroku CLI. The `nonExistentFlags` property values in the parsed result needed to be appended to the parsed results' `argv` property. In addition, copy for the deprecation warning has been updated as well.
1. Pull down branch
2. Run `yarn && yarn build`
3. Link `heroku-cli-command` to local `Heroku CLI` via
Update `heroku/cli`'s `package.json` with `"@heroku-cli/command": "file:/path/to/local/heroku-cli-command",`
4. After saving the updated code, run `yarn && yarn prepack` …
> fix(W-16338640): Update logic for backwards compatibility for CLI commands

- src/api-client.ts
- src/command.ts
- test/api-client.test.ts
When we removed support for `heroku-cli-util` two shared behaviors implemented at the APIClient were lost:
- Showing warnings on `$stderr` when either `X-Heroku-Warning` or `Warning-Message` headers were set on the response.
- Showing debug information for HTTP request/responses and additionally their headers, when `HEROKU_DEBUG` and `HEROKU_DEBUG_HEADERS` were respectively set to `1` or `true`.
Here we reintroduce those behaviors in the code for the new APIClient implemented on `@heroku-cli/command`
- Fetch this branch.
- Run `yarn && yarn build && yarn link` on your local `heroku-cli-command` workspace.
- Then change to your local workspace for the Heroku `cli` repo.
- Run `yarn link -p <path-to-your-heroku-cli-command-workspace>`.
- Run `yarn && yarn build`.
- Run ```HEROKU_DEBUG=1 …
```
> Adding missing debug and warning behaviors to APIClient

- package.json
- yarn.lock
We're seeing some issues with plugin installation and the CLI that seem to arise from not being able to find `yargs-parser`. This hopefully will address that.
> Move yargs into dependencies

- src/api-client.ts
- test/api-client.test.ts
This PR fixes the accumulation of requestIds in the header causing a header overflow error in long running poll operations. These have been observed to be larger than 8k (Node default max) in commands such as pg:wait
This PR limits the `Request-Id` header size to 7k which allows 1k for other header data. If the 7k limit is exceeded, the `Request-Id` is stripped of all previous values and is started over.
Note that a side effect of this is that long running poll operations now have the potential of fracturing the API call 'story' in tracking data.
1. build & pack (`npm run build && npm pack`)
2. install the packed tarball in the Heroku CLI project
3. comment out the `break` statement in packages/cli/src/commands/ps/wait.ts
4. run the command and let it go a while
5. OBSERVE - no header …
> fix(W-17812967): Heroku-cli-command: Header overflow

- package.json
- yarn.lock
[WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002EAIsvYAH/view)
Bumps the version of `http-call` in order to allow for redactions of the `x-addon-sso` header and anything that is returned from `/sso` endpoints. For more info see https://github.com/heroku/http-call/pull/68.
> feat: bump http-call to enable sso and token redactions

- src/api-client.ts
- src/vars.ts
- test/api-client.test.ts
- test/vars.test.ts
[W-19264912](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002JfNJOYA3/view)
This PR adds domain validation for making outbound requests. Authentication will only happen for valid domains, and host resolution will only work for valid domains, otherwise defaulting to heroku.com
1. Pull down this branch and `npm install && npm run build`
2. `HEROKU_HOST=bogus-domain.com npm run example whoami`
> W-19264912 feat: add domain name validation for outgoing requests

- src/api-client.ts
- src/vars.ts
- test/api-client.test.ts
- test/vars.test.ts
Applies the changes from #218 to a branch of this library that supports oclif/core v2.
This PR adds domain validation for making outbound requests. Authentication will only happen for valid domains, and host resolution will only work for valid domains, otherwise defaulting to heroku.com
> feat: add domain name validation for outgoing requests

- src/api-client.ts
- src/vars.ts
This change updates the oclif (not to be confused with oclif/core) from 2.2.5 to 4.22.5 and resolves related critical dependencies while maintaining core functionality. 
```
git checkout mm/fix-validated-domain
npm install && npm run build
```
run the following commands
```
npm install && npm run build
HEROKU_HOST=heroku.com npx ts-node examples/login.ts
HEROKU_HOST=herokai.com npx ts-node examples/login.ts
HEROKU_HOST=fakeheroku.com npx ts-node examples/login.ts
```
Note errors should appear only for fakeheroku.com. 
Gus Work Item: [W-19527406](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002LBNFaYAP/view) (Heroku internal)
> fix: v11 core v2 - updating to include an alternate url when api.url.com does not exist | W-19527406
